sul-dlss/dlme

.rubocop.yml, Rakefile, app/controllers/catalog_controller.rb, app/controllers/dlme_jsons_controller.rb, app/models/dlme_json.rb, app/resource_builders/dlme_json_resource_builder.rb, app/views/dlme_json/_form.html.erb, config/environments/test.rb, config/initializers/spotlight_initializer.rb, config/locales/en.yml, config/routes.rb, spec/features/add_dlme_json_spec.rb, spec/fixtures/json/embeddable.json, spec/fixtures/json/iiif-single-image.json, spec/fixtures/json/link-only.json, spec/rails_helper.rb, spec/resource_builders/dlme_json_resource_builder_spec.rb
=> Add a DLME intermediate representation resource

app/controllers/catalog_controller.rb
=> Add facet fields to solr request

config/initializers/riiif.rb
=> Use Riiif::HTTPFileResolver for fetching and rendering S3-hosted resources

app/controllers/catalog_controller.rb, app/models/solr_document.rb, app/resource_builders/dlme_json_resource_builder.rb, spec/models/solr_document_spec.rb, spec/resource_builders/dlme_json_resource_builder_spec.rb
=> Index all the things and display a IIIF viewer

app/controllers/catalog_controller.rb, app/models/solr_document.rb, app/views/catalog/_viewer_default.html.erb, config/initializers/oembed_providers.rb, spec/models/solr_document_spec.rb, spec/views/catalog/_viewer_default.html.erb_spec.rb
=> Add an oembed viewer and prefer it over IIIF when available

app/controllers/catalog_controller.rb, app/resource_builders/dlme_json_resource_builder.rb, spec/resource_builders/dlme_json_resource_builder_spec.rb
=> Finish metadata discovery short-list

Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb, app/processors/autolink.rb, config/initializers/blacklight.rb, spec/processors/autolink_spec.rb
=> Autolink field

lib/traject/macros/mods.rb, lib/traject/mods_config.rb, spec/import/mods_transform_spec.rb
=> adding the mods_transform_spec test per @cbeer

app/jobs/met_csv_import_job.rb, app/jobs/met_csv_transform_job.rb, bin/fetch_and_import, config/settings.yml, spec/jobs/met_csv_import_job_spec.rb, spec/jobs/met_csv_transform_job_spec.rb
Adds the jobs for MetCsv import and transform. Adds the job call to bin/fetch_and_import.
=> Add MetCsvImportJob and MetCsvTransformJob

app/jobs/met_csv_transform_job.rb, app/jobs/mods_transform_job.rb, app/jobs/tei_transform_job.rb, spec/jobs/met_csv_transform_job_spec.rb, spec/jobs/mods_transform_job_spec.rb, spec/jobs/tei_transform_job_spec.rb
Addressing: https://app.honeybadger.io/projects/53082/faults/34444582
=> Add Rails.root path to tranform jobs

.rubocop.yml, app/processors/autolink.rb, spec/processors/autolink_spec.rb
Ref https://app.honeybadger.io/projects/53082/faults/34442670
=> Handle mailto links

app/assets/stylesheets/application.css, app/assets/stylesheets/blacklight_overrides.scss, app/assets/stylesheets/dlme.scss, app/controllers/catalog_controller.rb, config/environments/development.rb
=> Hide tools

bin/fetch_and_import
Traject doesn't work with autoloading
See https://github.com/traject/traject/issues/142
=> Force eager loading when we're using traject

lib/traject/macros/tei.rb, lib/traject/tei_config.rb, spec/import/tei_transform_spec.rb
Adds the TEI mapping configuration for import.
=> Add TEI Mapping tranform configuration

app/models/solr_document.rb, app/views/catalog/_viewer_default.html.erb, spec/views/catalog/_viewer_default.html.erb_spec.rb
=> Viewer should fallback to a thumbnail image

app/views/catalog/_viewer_default.html.erb, spec/views/catalog/_viewer_default.html.erb_spec.rb
Fixes https://app.honeybadger.io/projects/53082/faults/34481424
=> Render thumbnails where solr has multiple values

config/settings.yml, config/settings/development.yml
Fixes https://app.honeybadger.io/projects/53082/faults/34418268
=> Avoid threads in traject

lib/traject/csv_reader.rb, spec/lib/traject/macros/csv_spec.rb
Fixes https://app.honeybadger.io/projects/53082/faults/34481413
=> Support dates that are just a year

app/helpers/catalog_helper.rb, app/views/catalog/_viewer_default.html.erb, spec/helpers/catalog_helper_spec.rb
Fixes https://app.honeybadger.io/projects/53082/faults/34482645
=> Handle suppress_link in render_thumbnail_tag override

.rubocop.yml, app/controllers/catalog_controller.rb, app/processors/join.rb, app/processors/paragraph.rb, config/initializers/blacklight.rb, spec/processors/autolink_spec.rb, spec/processors/join_spec.rb, spec/processors/paragraph_spec.rb
Join description and provinance with paragraphs and other fields with
linebreaks.
Fixes #182
=> Change the join logic for display fields

config/settings.yml
See https://app.honeybadger.io/projects/53082/faults/34485950#notice-summary
=> Fix typo in configuration

README.md, config/settings.yml, config/traject.rb, docs/mappings.md, lib/traject/fgdc_config.rb, lib/traject/macros/dlme.rb, lib/traject/macros/fgdc.rb, lib/traject/macros/mods.rb, lib/traject/tei_config.rb, spec/fixtures/fgdc/HARVARD.SDE2.AFRICOVER_EG_RIVERS.fgdc.xml, spec/import/fgdc_transform_spec.rb
=> Fgdc mappings

Gemfile, Gemfile.lock, app/assets/stylesheets/application.css, app/assets/stylesheets/footer.scss, app/views/shared/_footer.html.erb
=> Updated footer

lib/traject/macros/tei.rb, lib/traject/tei_config.rb, spec/import/tei_transform_spec.rb
=> Update TEI mapping

app/assets/javascripts/application.js
Hopefully this fixes problems with CSP & Jquery 1
Ref #136
=> Upgrade to jQuery 3.

app/views/harvests/index.html.erb
This will allow the table to layout in a narrower way
Fixes #206
=> Allow headers to break on underscore

lib/traject/csv_config.rb, lib/traject/fgdc_config.rb, lib/traject/iiif_config.rb, lib/traject/macros/csv.rb, lib/traject/macros/dlme.rb, lib/traject/macros/extraction.rb, lib/traject/macros/json.rb, lib/traject/macros/xml.rb, lib/traject/met_csv_config.rb, lib/traject/mods_config.rb, lib/traject/numismatic_csv_config.rb, lib/traject/penn_egyptian_config.rb, lib/traject/tei_config.rb, spec/lib/traject/macros/extraction_spec.rb
=> Pull out a TransformPipeline class with steps for every option

db/migrate/20170829215442_change_type_of_taggings_taggable.rb, db/schema.rb
See https://github.com/projectblacklight/spotlight/issues/1827
Fixes #224
=> Revert acts-as-taggable-on migration to use integer columns

app/jobs/create_resource_job.rb
=> Refactor CreateResourceJob so it doesn't spin off a second job.

app/controllers/catalog_controller.rb
=> Add more admin / qa facets

lib/traject/macros/met_csv.rb
Replaces '3D' with 'Image' for met edm_type
=> Update edm_type from 3D to Image

app/assets/stylesheets/dlme.scss, app/assets/stylesheets/footer.scss, app/assets/stylesheets/variables.scss, app/views/shared/_footer.html.erb
- Improves the footer at very narrow viewport size
- Adjusts a few elements to look better in mobile viewports (e.g., wraps site title)
- Adds a few more visual updates to work better with the DLME theme
----
=> Visual design refinements

docs/README.md, docs/add_data_source.md
=> Add step by step guide for adding a data source to DLME

docs/basic_config_examples.md
=> First draft of generic configuration examples

lib/traject/macros/tei.rb
Ref https://app.honeybadger.io/projects/53082/faults/34547776
Fixes #289
=> Do a nil check on the node prior to tranforming it.

app/views/shared/_footer.html.erb
=> Make the email address link a mailto link

docs/frameing_statement.md
Adds the framing statement we wrote before starting development work to the project docs.
=> Add Framing Statement

lib/traject/macros/numismatic_csv.rb, lib/traject/numismatic_csv_config.rb, spec/import/numismatic_csv_transform_spec.rb
Updates the Numismatic 'Provided By' facet value to be 'Islamic Department, American Numismatic Society'
closes #234
=> Fixes Numismatic 'Provided By' Facet

Gemfile, Gemfile.lock
=> Install a js runtime that will support autoprefixer

Gemfile, Gemfile.lock, spec/factories/dlme_jsons.rb, spec/factories/harvested_resources.rb, spec/factories/harvests.rb, spec/factories/pipelines.rb, spec/factories/resource_contents.rb, spec/rails_helper.rb
=> Upgrade FactoryGirl to FactoryBot

lib/traject/bnf_bo_config.rb, lib/traject/bnf_cealex_config.rb, lib/traject/bnf_ebaf_config.rb, lib/traject/bnf_ideo_config.rb, lib/traject/bnf_ifao_config.rb, lib/traject/bnf_ifea_config.rb
@peetucket search and replace added LOC_NS in the middle of translation map.
=> fix search and replace error in translation map

app/processors/join.rb, spec/processors/join_spec.rb
This becomes useful once we have
https://github.com/projectblacklight/blacklight/pull/1756
Ref #202
=> Join without html tags

Gemfile, Gemfile.lock, README.md, app/controllers/transforms_controller.rb, app/services/transform_notification.rb, app/views/shared/_site_sidebar.html.erb, app/views/transforms/show.html.erb, config/locales/en.yml, config/routes.rb, config/settings.yml, spec/controllers/transforms_controller_spec.rb, spec/services/transform_notification_spec.rb
=> Send a message to sns when the button is pushed

config/locales/en.yml
Required by https://github.com/projectblacklight/spotlight/commit/c69c530a8f32c35323d07e3e44b3373e9a98b532
Fixes #403
=> Update translation for Spotlight 2

.travis.yml, Dockerfile, Gemfile.lock
=> Upgrade to bundler 2.0

README.md
=> Add diagram for new architecture to the readme

docs/application_profile.md
This seems clearer to me. Let me know if you think it should change or stay as it was before.
=> edit application-profile

Gemfile.lock, app/controllers/s3_harvester_controller.rb, app/models/dlme_json.rb, spec/controllers/s3_harvester_controller_spec.rb
=> Prevent duplicate items

Gemfile, Gemfile.lock
=> There is no need to deploy v8 on Docker, we have Node

app/controllers/transforms_controller.rb, config/locales/en.yml, spec/controllers/transforms_controller_spec.rb
=> Notifies user when transform request sent.

db/migrate/20190227145747_drop_harvested_resources.rb, db/schema.rb
=> Drop harvested resource database tables

app/controllers/transforms_controller.rb, app/services/transform_notification.rb, app/views/transforms/show.html.erb, spec/controllers/transforms_controller_spec.rb, spec/services/transform_notification_spec.rb
=> Allows specification of data_dir to request partial transform.

docs/README.md
Remove note that says it isn't.
Ref #437
=> Multi-record XML handling is currently supported

app/controllers/transform_results_controller.rb, config/application.rb, lib/middleware/fix_sns_json_middleware.rb, spec/rails_helper.rb, spec/requests/transform_result_spec.rb
Rails knows how to parse JSON responses.  Also changed to a request
test.
=> Refactor the TransformController

docker/Dockerfile.worker
=> Add Node to the worker dockerfile

app/services/transform_notification.rb, spec/services/transform_notification_spec.rb
=> Switches transform message to json to support sending blank data_dir.

Gemfile.lock
This should fix problems with redirecting with a flash
Fixes #455
=> Update to spotlight 2.3.3

.env, README.md, app/controllers/s3_harvester_controller.rb, app/jobs/fetch_resources_job.rb, config/environments/development.rb, config/locales/en.yml, docker-compose.yml, docker/Dockerfile.worker, spec/controllers/s3_harvester_controller_spec.rb, spec/jobs/fetch_resources_job_spec.rb
=> Switches to background loading of resources from S3.

docker/Dockerfile.worker
Add git to the worker image so that circle can build from non master branches in the Gemfile
=> Add git to the worker image

Gemfile, Gemfile.lock, docker/Dockerfile.worker
=> Use released version of Spotlight and Blacklight

config/sidekiq.yml.erb
Set the sidekiq concurrency to test performance.
=> Set sidekiq concurrency to 10

app/views/_user_util_links.html.erb
=> Added link to transform data under user links.

solr/config/solrconfig.xml
This removes unused (spellcheck) features of the solrconfig as well as increase the batch size used for indexing.
=> Update solr config to remove unused features

README.md
Part of the documentation for #500
=> Add deployment information to the README

app/controllers/s3_delete_controller.rb, app/jobs/delete_resources_job.rb, app/resource_builders/dlme_json_resource_builder.rb, app/views/s3_delete/new.html.erb, app/views/spotlight/catalog/_admin_header.html.erb, config/locales/en.yml, config/routes.rb, docker/Dockerfile.worker, spec/controllers/s3_delete_controller_spec.rb, spec/jobs/delete_resources_job_spec.rb, spec/resource_builders/dlme_json_resource_builder_spec.rb
=> Create a way to delete objects

docker-compose.yml
I am unable to connection to the app on localhost without this setting. However, I will defer to the group, if this is somehow only a problem I'm seeing, I'm :+1: with leaving this out of docker-compose and just noting it as a local environment requirement.
=> HOST Variable needed in order to connection to localhost

app/views/shared/_footer.html.erb
CLIR recently moved office locations and the footer address/phone number needs to be updated.
=> Update footer address for CLIR offices

docker/Dockerfile
This should fix the master build.
=> Fix build related to bundler

README.md
also configured circleci to send coverage stats to coveralls.
=> hook up coverage to correct CI service, fix badges

app/jobs/delete_resources_job.rb, spec/jobs/delete_resources_job_spec.rb
=> Ensure the record is found before operating on it

app/assets/javascripts/transform_result.js, app/controllers/transform_results_controller.rb, app/views/transform_results/show.json.jbuilder, app/views/transforms/show.html.erb
=> Add buttons to paginate the transform data results

app/views/dlme_s3s/_form.html.erb
This just gets in the way of pasting in the new value
Fixes #538
=> Remove https:// as the default value for the url

app/jobs/fetch_resources_job.rb, spec/jobs/fetch_resources_job_spec.rb
To show what errors are happening, to make troubleshooting and remediation easier.
no.
=> Surface JSON validation errors in exceptions

app/assets/stylesheets/blacklight.scss
=> Constrain thumbnail images

config/initializers/new_framework_defaults_5_2.rb
Fixes #615 
The only "dangerous" setting I can see is the sqlite boolean change, but that should only affect local development anyway.
=> Use new Rails 5.2 framework defaults

README.md
Cloes #612
To update the README w/ information about recent changes to the local development environment.
Yes, in fact, that's all this change is! 📚
=> Update README with details about how to run outside of Docker.

config/initializers/action_mailer.rb
=> Add mailer configuration for the SMTP/SES endpoint

Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/footer.scss, app/assets/stylesheets/rtl.scss, app/helpers/blacklight_helper.rb, vendor/assets/stylesheets/bootstrap/_rtl.scss
=> Set dir='rtl' for Arabic; part of #609

app/controllers/catalog_controller.rb
At least for the ones that have been consistently translated so far:
- lang
- edm_type
- agg_provider
- agg_data_provider
=> Toggle between English and Arabic-language facets

app/assets/stylesheets/rtl.scss
=> Align dts to the left in RTL mode

app/assets/stylesheets/rtl.scss
=> Flip the filter name and value in the constraint bar under RTL

app/controllers/catalog_controller.rb, app/helpers/application_helper.rb, config/locales/en.yml, spec/helpers/application_helper_spec.rb
=> Display both Gregorian and Hijri dates on results and show pages

app/controllers/catalog_controller.rb, app/processors/bidi_wrap.rb, spec/processors/bidi_wrap_spec.rb
=> Add a configuration flag to disable BIDI wrapping

Gemfile, Gemfile.lock
https://github.com/projectblacklight/spotlight/pull/2307 should resolve the build issues.
A new version of blacklight-gallery and blacklight-hierarchy were released
Nope
=> Update blacklight-gallery and blacklight-hierarchy

config/settings.yml
See sul-dlss/dlme-transform#395
=> Sync acceptable_bcp47_codes with dlme-transform

app/controllers/catalog_controller.rb
… to build up the complete tree, otherwise some results could be truncated.
Fixes #740.
=> Set the facet limit for hierarchical facets to -1 (unlimited)

config/initializers/spotlight_initializer.rb
=> Configure the autocomplete solr request

app/assets/stylesheets/bootstrap-overrides.scss, app/views/catalog/_show_with_viewer.html.erb, config/locales/en.yml, spec/views/catalog/_show_with_viewer.html.erb_spec.rb
=> Add link text 'View on contributor website' to link back to the contributing site;

.rubocop.yml, app/controllers/s3_harvester_controller.rb, app/jobs/delete_resources_job.rb, app/jobs/fetch_resources_job.rb, app/services/ndjson_normalizer.rb, bin/yarn, spec/services/ndjson_normalizer_spec.rb
if a blank line exists in the metadata, the delete resources job will fail.
=> fixes issue where blank lines in the data cause a delete failure

.rubocop.yml, app/controllers/catalog_controller.rb, app/controllers/concerns/multilingual_locale_aware_field.rb
=> Add multilingual support for all text fields

Gemfile.lock
Small follow up PR for updates.
=> Follow up for a security update

app/javascript/packs/mirador.js, babel.config.js, package.json, postcss.config.js, yarn.lock
Fixes #733 , paired w/ @camillevilla on this
=> Update mirador to support IE/Edge

config/settings.yml
=> Add locale as a default url parameter for mailers

app/assets/stylesheets/rtl.scss
=> Update styling for RTL facet remove icon display fixes #788

docker/Dockerfile
Circle build is failing on this command.
=> Add bundle exec to fix build

Gemfile, Gemfile.lock, config/i18n-tasks.yml, config/locales/ar.yml, config/locales/en.yml, spec/i18n_spec.rb
To help generating the list of keys that need to be translated in the app (as well as general i18n health)
=> Add and configure the i18n tasks gem

config/locales/ar.yml
Add Arabic translations for new English fields on stats page
n/a
=> Add Arabic translations for stats page

package.json, yarn.lock
Update to beta.2 for better RTL support
=> Update to Mirador v3.0.0-beta.2

package.json, yarn.lock
=> Update Mirador to fix scrolling issue

docs/application_profile.md
=> Include dlme_source_file in application profile

yarn.lock
=> Update yarn dependencies for security warnings

app/helpers/application_helper.rb, config/i18n-tasks.yml, config/locales/en.yml, spec/helpers/application_helper_spec.rb
=> Change negative numbers to BH and BCE

app/controllers/spotlight/home_pages_controller.rb
=> Authorize range limit actions from exhibit home pages

config/initializers/spotlight_initializer.rb
Closes #758
See sul-dlss/exhibits#1296 for an example of how we configured this in exhibits.
=> Configure spotlight upload title to solr field mapping

app/controllers/catalog_controller.rb
Related to #903
Probably good to get this merged before translations and configuration starts happening in earnest.
=> Use field keys without spaces

app/views/shared/_header_navbar.html.erb, app/views/shared/_user_util_links.html.erb
This fixes an unreported issue where when clicked the navbar user utils the color had issues (a BS4 update thing). Also adds in the Spotlight aria-label
=> Make the navbar more like Spotlight re: BS4 class approach

app/views/shared/_site_sidebar.html.erb, app/views/transforms/show.html.erb, config/locales/en.yml
=> Add the sidebar to the transforms page, and include a link to the exhibit home page

.rubocop_todo.yml, app/controllers/catalog_controller.rb, app/helpers/application_helper.rb, app/processors/autolink.rb, app/processors/bidi_wrap.rb, app/processors/join.rb, app/processors/paragraph.rb, spec/controllers/catalog_controller_spec.rb, spec/processors/autolink_spec.rb, spec/processors/bidi_wrap_spec.rb, spec/processors/join_spec.rb, spec/processors/paragraph_spec.rb
=> Disable BIDI wrapping in non-HTML contexts

app/assets/stylesheets/dlme.scss, app/views/statistics/_items.html.erb, spec/views/statistics/_items.html.erb_spec.rb
=> Add a caret to  the statistics page; fixes #917

app/assets/stylesheets/dlme.scss, app/assets/stylesheets/variables.scss
=> Remove custom breadcrumb margins fixes #941

app/controllers/spotlight/home_pages_controller.rb, config/locales/blacklight.en.yml, spec/features/facet_titles_spec.rb
=> Setup different facet sidebar headings fixes #939

app/assets/stylesheets/blacklight.scss, app/assets/stylesheets/dlme.scss, app/assets/stylesheets/footer.scss, app/assets/stylesheets/mirador.scss, app/assets/stylesheets/variables.scss
Closes #887.
Updated font sizing to account for small size of Markazi font and made various other styling updates.
I'll do more fine-tuning as we go but this should be another good step forward.
---
---
=> Update font sizing and other styling

app/controllers/catalog_controller.rb, spec/features/things_can_be_indexed_spec.rb
=> Hide some facets from non-curators

app/javascript/packs/mirador.js, app/views/catalog/_mirador_default.html.erb, config/webpack/environment.js, package.json, yarn.lock
Gets in many of the changes discussed in #942
=> Update mirador and set language and direction

app/helpers/application_helper.rb, spec/features/contextual_message_spec.rb
=> Don't show the contextual pane if there wasn't a search query

package.json, yarn.lock
=> Update Mirador to v3.0.0-beta.10

app/controllers/catalog_controller.rb
I'm not able to recreate this issue locally, but for some reason it is happening in our deployed dev environment.
=> Safe navigate has_range_limit_parameters? fixes #1119

Gemfile, Gemfile.lock
=> Pin gallery until Blacklight v7.15.0

app/controllers/catalog_controller.rb
=> Update facet config to make sure its available in admin menu

app/assets/javascripts/range_limit_config.js, app/controllers/catalog_controller.rb, app/helpers/application_helper.rb, app/views/blacklight_range_limit/_custom_range_limit_panel.html.erb, config/locales/ar.yml, spec/features/custom_range_limit_spec.rb
To resolve the issue reported where multiple date range switching caused an error
**NOTE** This pull request also updates the conditionality to use if instead of show and provides the Arabic translation of calendar.
=> Fixes #1134 resolving the issue with multiple switching back and forth date range

app/views/blacklight_range_limit/_custom_range_limit_panel.html.erb
=> Update range limit column responsive sizing

app/views/record_feedback/new.html.erb, config/i18n-tasks.yml, config/locales/ar.yml, config/locales/en.yml, spec/features/record_feedback_spec.rb
=> Update some Arabic translations now that we've received them

Gemfile.lock
I'm sure we might do some style tweaking but this is how it looks out of the box in DLME.
=> Update Spotlight to enable new Home page browse categories

Gemfile.lock
=> Update to Spotlight latest

app/assets/stylesheets/rtl.scss, app/views/spotlight/shared/_report_a_problem.html.erb
=> Fixes #1176 Update contact form alignment

.gitignore
https://www.alanvardy.com/post/puma-server-not-loading 🤷
=> Add the tmp/pids directory

.dockerignore
=> Also un-dockerignore the tmp/pids directory

spec/controllers/transform_results_controller_spec.rb, spec/factories/transform_results.rb, spec/requests/transform_result_spec.rb
Added a failing test here that would have caught the regression fixed in #1186
=> Add some more tests around TransformResults

app/controllers/s3_delete_controller.rb, app/controllers/s3_harvester_controller.rb
=> Include SpotlightController rather than subclassing from

app/views/record_feedback/new.html.erb
Fixes #1194 , with https://github.com/projectblacklight/spotlight/pull/2635 (probably?)
=> Use explicit main_app routing for the record contact form

app/views/statistics/show.html.erb
=> Reorder the statistics page

Gemfile, Gemfile.lock, app/models/dlme_json.rb, app/resource_builders/dlme_json_resource_builder.rb, db/migrate/20210202002637_create_job_trackers.spotlight.rb, db/migrate/20210202002638_create_events.spotlight.rb, db/schema.rb, spec/features/contextual_message_spec.rb, spec/features/custom_range_limit_spec.rb, spec/features/facet_titles_spec.rb, spec/features/metadata_collapse_spec.rb, spec/features/mirador_viewer_spec.rb, spec/features/record_feedback_spec.rb, spec/features/things_can_be_indexed_spec.rb, spec/rails_helper.rb
Requires https://github.com/projectblacklight/spotlight/pull/2636
=> Use the ETL pipeline to index documents

app/assets/stylesheets/rtl.scss
=> Fixes #1209 by adding RTL class modifications

Gemfile, Gemfile.lock, config/environments/production.rb
This was lost with the Rails 6.1 update
=> Restore production environment configuration

Gemfile.lock
=> Update to latest version of Spotlight

app/jobs/delete_resources_job.rb
Continued work to debug the timing of background jobs.
=> Add additional logging to the delete_resources_job

app/jobs/delete_resources_job.rb, app/services/resource_remover.rb, lib/tasks/cleanup.rake, spec/factories/dlme_jsons.rb, spec/services/resource_remover_spec.rb
closes sul-dlss/dlme-transform#702
a description was added for the new rake task that makes this new functionality available.  can also add to the README, if desired.  i didn't see anything similar in the README, but this also seems like the app's first custom rake task?
=> Delete all resources

app/controllers/catalog_controller.rb, app/controllers/dlme_bulk_actions_controller.rb, app/jobs/delete_search_results_job.rb, app/views/spotlight/catalog/_delete_resources.html.erb, config/locales/ar.yml, config/locales/en.yml, config/routes.rb, spec/features/bulk_resource_delete_spec.rb
closes sul-dlss/dlme-transform#703
see also https://github.com/sul-dlss/dlme/issues/1303
N/A?  but happy to update docs if it turns out i should.
=> delete items using search results

app/presenters/dlme_thumbnail_presenter.rb
Fixes https://app.honeybadger.io/projects/53082/faults/80088751
=> Do not try to resolve invalid thumbnail URLs

app/assets/stylesheets/blacklight_gallery.scss
=> Increase font size of gallery caption and counter

.circleci/config.yml
https://circleci.com/docs/2.0/caching/#full-example-of-saving-and-restoring-cache
=> Use CircleCI best practices for partial bundler caching

.circleci/config.yml, Gemfile, Gemfile.lock, docker/Dockerfile, docker/Dockerfile.worker, package.json, yarn.lock
Requires #1404 (webpacker drops old node-sass dependency)
=> Test with ruby 2.7.5

app/models/statistics_dashboard.rb, app/views/statistics/_items.html.erb, spec/models/statistics_dashboard_spec.rb
Fixes issue reported in comment on #1349
=> Fix language facet query link generation on statistics page.

.circleci/config.yml
=> Use the aws cli orb

.circleci/config.yml
... to avoid conflicting with the UAT one.
Fixes a regression by restoring the previous value:
https://github.com/sul-dlss/dlme/blob/2.2.21/.circleci/config.yml#L264
=> Use a complicated regex for the DLME -stage cluster

.circleci/config.yml, config/initializers/okcomputer.rb, docker/Dockerfile, docker/Dockerfile.worker
- Add git info to docker builds
- Expose git info via okcomputer status check
- Bake git info into CI docker builds
fixes #1434
=> Add git info to builds

README.md
- Adds info about configuring and using ECS Exec
- Adds info about deployment environments on AWS
- Adds recipe for inspecting local docker images
Closes #1445
=> Update deployment documentation

.github/pull_request_template.md
Because we're not using this template.
=> Remove the PR template.

app/controllers/catalog_controller.rb
=> Use POST requests when talking to Solr

app/assets/stylesheets/dlme.scss
Fixes #1293 
Edit `dlme.scss` with `--webkit-line-clamp` as suggested by @ggeisler - thanks!
=> Add CSS to truncate titles

app/views/spotlight/shared/_report_a_problem.html.erb
=> Force-encode the current URL to try to correct some weird bingbot behavior

app/resource_builders/dlme_json_resource_builder.rb, spec/resource_builders/dlme_json_resource_builder_spec.rb
=> Pad digits in the sortable title so they sort 'naturally'

app/resource_builders/dlme_json_resource_builder.rb, spec/resource_builders/dlme_json_resource_builder_spec.rb
=> Add min/max fields for date sorting

app/models/statistics_dashboard.rb, app/views/statistics/show.html.erb, config/locales/ar.yml, config/locales/en.yml, spec/features/statistics_spec.rb, spec/models/statistics_dashboard_spec.rb, spec/views/statistics/_contributors.html.erb_spec.rb
=> Rename data/item contributors

solr/config/schema.xml
=> Add `sortMissingLast="true" ` to numeric + date field types

app/controllers/catalog_controller.rb
=> Configure agg_data_provider_collection_ssim to be language aware

app/helpers/application_helper.rb, app/views/statistics/_contributors.html.erb, app/views/statistics/_items.html.erb, spec/helpers/application_helper_spec.rb
=> Update facet linking to use non-deprecated methods

app/presenters/dlme_thumbnail_presenter.rb, app/views/catalog/_show_with_viewer.html.erb, spec/presenters/dlme_thumbnail_presenter_spec.rb
Part of https://github.com/sul-dlss/dlme/issues/1457
=> Use the DocumentPresenter instead of deprecated #has_thumbnail? helper

app/views/dlme_jsons/edit.html.erb, app/views/dlme_jsons/index.html.erb, app/views/dlme_jsons/show.html.erb
=> Update DlmeJson templates so they display right

README.md
Fixes #1492
Happy to take edits or additional info that others think would be helpful to add here.
=> Add info on fixture data to README

app/controllers/catalog_controller.rb, app/controllers/session_displays_controller.rb, app/helpers/application_helper.rb, app/helpers/blacklight_helper.rb, app/views/shared/_contextual_date_sort_info.html.erb, app/views/shared/_contextual_result_info.html.erb, config/locales/en.yml, spec/controllers/session_displays_controller_spec.rb, spec/features/contextual_date_sort_message_spec.rb, spec/features/contextual_result_message_spec.rb, spec/helpers/application_helper_spec.rb
=> Configure date sort; add contextual alert.

app/controllers/catalog_controller.rb
=> Set agg_data_provider_collection to appear in curator list of configurable metadata fields.

app/models/statistics_dashboard.rb, spec/features/statistics_spec.rb, spec/models/statistics_dashboard_spec.rb, spec/views/statistics/_contributors.html.erb_spec.rb
=> Use agg_data_provider_collection_id_ssim for collection count.

.circleci/config.yml, docker/Dockerfile
I'm not sure if there's a reason we didn't do this in the first place 🤷‍♂️
=> Build + test with ruby 3

README.md
- Add ruby version badge to README
=> Document supported ruby version

config/sidekiq.yml.erb
We think 10 was... too much for solr. See #1322
=> Lower sidekiq concurrency

solr/config/solrconfig.xml
I don't know if this is a useful idea, but I'm not sure it can hurt either 🤷‍♂️
=> Apply autocommit settings from e.g. searchworks

config/initializers/rack-attack.rb
=> Throttle searches

solr/config/schema.xml
=> Turn on DocValues for str, bool, and number fields

docker/invoke_fetch_s3.sh
This supports triggering the indexing of resources from airflow in AWS.
=> Update fetch s3 invoke to use updated rake task

docker/invoke_fetch_s3.sh
This is a temporary change that I would like to get into AWS to debug the indexing invocation via airflow.
=> Add trace to index rake command for debugging

Gemfile, Gemfile.lock, config/environments/development.rb
It is no longer needed. See https://github.com/rails/rails/commit/e34300a921a910c60cd4064038b0817fe0e0ab18
=> Remove the listen gem

Gemfile, Gemfile.lock
The bug that prevented us from updating it has been resolved
=> Update rubocop rails

.circleci/config.yml
See https://discuss.circleci.com/t/git-checkout-during-build-suddenly-no-longer-working/46680
=> Move checkout to the first step of the circle-ci config

Gemfile, Gemfile.lock
=> Upgrade to sidekiq 7 and redis 5

.circleci/config.yml
=> Stop updating ECS when building

Capfile, Gemfile, Gemfile.lock, config/deploy.rb, config/deploy/prod.rb, config/deploy/stage.rb
=> Deploy code locally via Capistrano

config/initializers/rack-attack.rb
Use throttled_responder instead
=> Stop using deprecated Rack::Attack.throttled_response

Jenkinsfile
=> Add continuous deployment to stage and prod

app/assets/stylesheets/blacklight_gallery.scss
See https://github.com/sul-dlss/exhibits/commit/6d9ba0c4723837f539de120a9cce27becc864156
=> Avoid including two copies of bootstrap

app/helpers/application_helper.rb
=> Avoid deprecated method path_for_facet

Gemfile, Gemfile.lock
=> Update redis and sidekiq (again)

app/controllers/catalog_controller.rb
=> Configure link_to_facet

app/assets/stylesheets/dlme.scss, app/views/shared/_header_navbar_masthead.html.erb, app/views/shared/_user_util_links.html.erb
=> Suppress the Contact and Sign-in links at narrow widths

app/assets/stylesheets/dlme.scss, app/components/document_metadata_component.html.erb, app/components/document_metadata_component.rb, app/components/owner_field_component.rb, app/components/owner_layout_component.rb, app/controllers/catalog_controller.rb, app/views/catalog/_contributor_link.html.erb, app/views/catalog/_show.html.erb, app/views/catalog/_show_with_viewer.html.erb, spec/components/document_metadata_component_spec.rb, spec/components/owner_field_component_spec.rb, spec/components/owner_layout_component_spec.rb, spec/rails_helper.rb, spec/views/catalog/_show_with_viewer.html.erb_spec.rb
=> Highlight item provider on the display page

spec/support/controller_level_helpers.rb
This module is not present in Blacklight 8.
=> Remove unnecessary include

app/controllers/api/api_controller.rb, app/controllers/api/harvests_controller.rb, app/controllers/harvests_controller.rb, app/services/ndjson_normalizer.rb, app/services/ndjson_upload.rb, config/locales/en.yml, config/routes.rb, spec/requests/api/create_harvest_spec.rb, spec/requests/create_harvest_spec.rb
=> Implement a simple API endpoint for initiating harvests

Gemfile, Gemfile.lock, app/assets/config/manifest.js, app/assets/javascripts/analytics.js, app/assets/javascripts/application.js, app/assets/javascripts/spotlight.js, app/javascript/entry.js, app/views/layouts/spotlight/base.html.erb, app/views/record_feedback/new.html.erb, app/views/spotlight/shared/_curation_sidebar.html.erb, app/views/spotlight/shared/_report_a_problem.html.erb, bin/importmap, config/importmap.rb, package.json, yarn.lock
=> Install turbo-rails

config/initializers/rack-attack.rb
=> Disable throttling for Stanford-local traffic

app/assets/stylesheets/dlme.scss
=> Ensure the admin dropdown is on top of the search input

Gemfile.lock
This restores the range limit histogram
=> Upgrade bl-range-limit

app/components/owner_field_component.rb, spec/components/owner_field_component_spec.rb
=> Fix layout for owner fields

Gemfile, Gemfile.lock, app/assets/config/manifest.js
=> Update blacklight-hierarchy and blacklight-gallery

app/assets/stylesheets/eastern_arabic_numeral_font.scss
It's a sprockets thing, but we aren't processing the css with sprockets anymore
=> Stop using font-url

app/controllers/catalog_controller.rb
=> Configure facet fields so that multilingual link_to_facet will work

config/deploy/prod.rb, config/deploy/review.rb
- Add cap deployment config for review environment
- Make review environment part of production
Closes #1761
=> Add data review environment config

app/assets/stylesheets/application.sass.scss
To reflect upstream changes: https://github.com/projectblacklight/spotlight/pull/3358
=> Remove empty sass file

app/assets/config/manifest.js
I think need to link these to unblock https://github.com/sul-dlss/dlme/pull/1918.
=> Link the OSD gem JS file

Gemfile, Gemfile.lock, app/assets/config/manifest.js
I think this may be a better temporary solution to get dep updates going again.
=> Pin openseadragon gem

config/initializers/rack-attack.rb, config/settings.yml
=> add redis cache store to rack-attack
