application_profile.md, spec/fixtures/json/embeddable.json, spec/fixtures/json/iiif-single-image.json, spec/fixtures/json/iiif-with-manifest.json, spec/fixtures/json/link-only.json
Adds four fixtures: 1) embeddable object (Sketchfab); 2) single IIIF image;
3) an IIIF resource w/ a manifest, and 4) one with a link only.
Also adds the draft application profile documentation.
=> Add JSON fixtures and application profile documentation

app/assets/stylesheets/blacklight.scss, app/controllers/catalog_controller.rb
=> Copy index styling from exhibits to align thumbnails a little better

cloudformation/stack.yaml
This will also control the sidekiq concurrency:
https://github.com/mperham/sidekiq/commit/52828e42123cc1c54b2a326bda5d00965ec05acb#diff-411201f0104d91346964914342a07cefR212
We hope this will fix sidekiq errors like:
> ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use
 
=> Set RAILS_MAX_THREADS

config/environments/production.rb
Fixes #119, among others, where javascript doesn't load via http.
=> Force SSL except for health checks (e.g. from the load balancer)

app/controllers/catalog_controller.rb, app/jobs/create_resource_job.rb, app/models/dlme_json.rb, app/models/pipeline.rb, app/resource_builders/dlme_json_resource_builder.rb, lib/traject/dlme_json_resource_writer.rb, spec/models/pipeline_spec.rb, spec/resource_builders/dlme_json_resource_builder_spec.rb
For now, this context may include these settings:
- command_line.filename (the original provided name when running traject)
- source (used as a key for our import configuration)
- position (record N of M in a batch)
- harvest_id
- harvest_resource_id
=> Record additional context within the DlmeJson and index it appropriately

app/assets/stylesheets/variables.scss, app/views/harvests/index.html.erb, config/locales/en.yml
Very minor updates:
- Change label for sidebar menu item to "Manage data" from "Harvests" so label is consistent with other sidebar actions (label starts with a verb and matches primary title of page is goes to).
- Change label for table caption on the Harvests page (because the table includes more info than just number of files) and darken text (because it'll need more contrast with the visual design updates in #254).
=> Update Manage Data page and superadmin sidebar

config/settings.yml, spec/import/tei_transform_spec.rb
Updates the  for Penn Libraries to be 'University of Pennsylvania Libraries' for all datasets.
closes #281
=> Standardize Penn Libaries Names

config/settings.yml
We received METS data that includes paths for the thumbs and full-size images. This limits the indexing to just the MODS records for now.
=> Limit Princeton Movie Poster indexing to MODS

Dockerfile, README.md, config/environments/production.rb, docker-compose.yml
This:
- Adds a Dockerfile in order to register a docker image for the web app that will be usable in AWS, etc
- Adds a docker-compose.yml file that can be used in local development
- Turns off the force SSL (causes issues for local development)
- Updates README with instructions on setting up the database for local development
- Add SOLR to the docker-compose.yml
NOTE: DO NOT Merge this until confirmed we avoid the current CI/CD step.
=> Dockerize the web app

lib/traject/bnf_bo_config.rb, lib/traject/bnf_cealex_config.rb, lib/traject/bnf_ebaf_config.rb, lib/traject/bnf_ideo_config.rb, lib/traject/bnf_ifao_config.rb, lib/traject/bnf_ifea_config.rb, lib/traject/bnf_salt_config.rb, lib/traject/macros/dlme.rb
Removing the NS caused this error: 
```
Error loading configuration file lib/traject/bnf_ideo_config.rb:20 NameError:uninitialized constant NS
lib/traject/bnf_ideo_config.rb:20:in `block in load_config_file'
```
If I remove the NS parameter from extract_xml I get this error:
```
Error loading configuration file lib/traject/bnf_ideo_config.rb:20 ArgumentError:wrong number of arguments (given 1, expected 2..3)
/Users/jtim/Dropbox/DLSS/DLME/dlme/lib/traject/macros/xml.rb:11:in `extract_xml'
lib/traject/bnf_ideo_config.rb:20:in `block in load_config_file'
```
I need help resolving this
=> readded namespace to bnf config files

config/initializers/translations.rb
This can occur if the app starts up ahead of the database or if we just want to compile assets
See: https://github.com/projectblacklight/spotlight/issues/2133
=> The application should not be dependent on a database at startup

config/application.rb
This avoids a deprecation warning for sqlite3 when testing
=> Use the 5.2 defaults

docker-compose.yml
This is a slapdash fix so that the container will come up.
We shouldn't need to pass the env var to this container once it's not building assets
=> Provide SECRET_KEY_BASE to sidekiq container

config/initializers/sidekiq.rb
Remove auth (password) from redis config as it is not set in AWS.
=> Set path and ID appropriately for redis

Gemfile
This prevents an error when building the sidekiq container:
```
ERROR: Service 'sidekiq' failed to build: The command '/bin/sh -c bundle config build.nokogiri --use-system-libraries     && bundle install --without development test' returned a non-zero code: 5
```
=> Sqlite only for dev/test

config/application.rb
ActionDispatch::Static is only used when RAILS_SERVE_STATIC_FILES is set
=> Add middleware relative to known middleware

.env, docker-compose.yml
Removed config in .env that we are not using. These came from orats
but we are not using the orats templates
=> Start redis without a password.

config/sidekiq.yml
The worker container is set to use config/sidekiq.yml.erb but there
was also a config/sidekiq.yml which was confusing.
=> Remove an unused config file

README.md
Completes #500 with a link to the terraform organization readme. The documentation has been placed there as it involves linking to private code.
=> Add link to terraform for deploy

config/initializers/spotlight_initializer.rb, config/settings.yml
Since we are running this in a container, we want to avoid including the PKCS12 key for google analytics in the public image. This allows us to pass a path to create the file and an S3 path to download the file in ENV variables and then grab the key file during initialization.
=> Add download of p12 key from S3 in spotlight_initializer

README.md
d'oh - typo.
Question:  circleci configs don't run tests on master, but that means coveralls badge is a bit wonky.  Should we run tests on master?
=> fix badge typo

Gemfile, Gemfile.lock
We do not deploy to Windows or JRuby environments, so remove these unnecessary lines that break aliases/functions wrapped around `bundle`.
=> Remove unused platforms from Gemfile

README.md
Includes:
* Remove tabs from `aws` commands because they make copy/paste not work (on some platforms)
* Add a setup step that makes clear AWS CLI needs to be installed
* Clarify that there is an assumption about having sibling directories in place for dlme-traject, dlme-transform, and dlme-metadata
* Map `/opt/traject` to dlme-transform's root, not dlme's root, so the `docker run` transform command works correctly
* Use `tmp/output/` to hold output so `output` doesn't show up to git as an untracked directory
To improve documentation.
Yes.
=> Spruce up documentation for first-time setup

app/views/transform_results/show.json.jbuilder, spec/requests/transform_result_spec.rb
Fixes #576
This commit makes sure the transform_results JSON *always* contains the `links` object. Without this change, `data.links` is undefined when the page initially loads which causes a JavaScript error that prevents the transformation results from rendering
n/a
=> Make sure transform_results view always defines links

app/controllers/s3_harvester_controller.rb, config/locales/en.yml, spec/controllers/s3_harvester_controller_spec.rb
Fixes sul-dlss/dlme-transform#158
This lets users know up front that their transformation batch contains duplicate rows, which may lead to a surprising count of items in the exhibit. Ran this idea by Jacob and he approves of the approach.
No.
=> Validate that S3 Fetch URL contains no duplicate identifiers

README.md, docs/README.md
=> Remove vestiges of dlme-traject repository

.rubocop.yml, app/jobs/fetch_resources_job.rb, spec/jobs/fetch_resources_job_spec.rb
`url` was not defined FetchResourcesJob#create_or_update_resource and this code path was not tested. Now we test it and `url` is defined.
no
=> Fix bug in FetchResourcesJob

.circleci/config.yml, Gemfile, Gemfile.lock, spec/features/admin_menu_spec.rb, spec/rails_helper.rb
Closes #613 
To add the ability to more closely test browser behavior in anticipation of some upcoming work around RTL.
These tests will run alongside other tests as well as follows our existing conventions, so hopefully no documentation should be required.
=> Add JS webdrivers + Add browser integration test

app/resource_builders/dlme_json_resource_builder.rb, spec/fixtures/json/iiif-single-image.json, spec/resource_builders/dlme_json_resource_builder_spec.rb
An additional wrinkle uncovered when dealing with multilingual fields: sending a hash along in a tokenized field makes Solr unhappy. This PR adds awareness of multilingual fields (using the IIIF-y language hash), and reaches into these hashes to construct lang-specific Solr fields with arrays as values. Also, make sure the derived sortable field logic can deal with these same fields.
no.
=> Handle multilingual tokenized fields

solr/config/schema.xml, solr/config/solrconfig.xml
Many dynamic field variants in the schema are commented out or unused. Some of the configurations are considered deprecated and/or have new defaults in current versions of Solr. This PR removes those to try to get a better picture of what's currently happening (and if we discover we need them, they're easy enough to add).
Also, bump thee `luceneMatchVersion` to get some of the relevancy ranking changes and other defaults, so we deal with them now instead of after putting extensive effort into relevancy tuning.
=> Clean and update the solr configurations

config/routes.rb
This should fix the 404 from https://spotlight.stage.dlmenetwork.org/exhibits/edit (and possibly similar errors).
=> Don't override spotlight's exhibit CRUD routes with application routes

app/resource_builders/dlme_json_resource_builder.rb, spec/resource_builders/dlme_json_resource_builder_spec.rb
In order to keep the app functional while fields are being transformed into language-tagged fields, keep on indexing them into the same old fields. This also is useful for some analytics and curation queries (e.g. show me all the things without titles)
=> Also index multilingual fields into a common field

docker/Dockerfile, docker/Dockerfile.worker
Without this, the build image step fails with:
> sh: git: not found
after we started pointing our app at the spotlight master branch
=> Install git into the app containers

docker/Dockerfile.worker
```
Error response from daemon: Dockerfile parse error line 23: unknown instruction: &&
Exited with code 1
```
=> Add a missing trailing slash to the worker dockerfile

app/controllers/catalog_controller.rb, config/settings.yml
Part of #630 
So we can begin to see the multilingual content that was indexed transformed/indexed before #589 is ready to be worked on (which will be the more complex logic of what is displayed when certain locales are chosen).
n/a
Note: This is more-or-less just a stop gap so that we can render the multilingual data that is available.  There is work going on both in DLME (for Empty values faceting purposes) and upstream in Blacklight (for features that will support multilingual field rendering) that will likely supersede this code in the long run
=> Add initial (basic) support for multilingual fields

config/environments/production.rb
The way that i18n fallbacks are configured was changed in i18n [v1.1.0](https://github.com/ruby-i18n/i18n/releases/tag/v1.1.0).
No.
=> Update i18n fallbacks config

app/mailers/application_mailer.rb, config/initializers/action_mailer.rb, config/initializers/devise.rb, config/settings.yml
This is the same pattern we're using in exhibits and it seems useful (and a little more flexible than the current one.) This will also require some terraform work to set the environment variables for the deploy.
Part of #626
=> Use settings to configure the action mailer options (e.g. from) and url options (e.g. host)

app/views/shared/_user_util_links.html.erb
=> Migrate user_util_links markup to bootstrap 4

app/assets/stylesheets/dlme.scss, app/assets/stylesheets/variables.scss
=> Update Bootstrap css overrides

Gemfile, Gemfile.lock, app/assets/javascripts/application.js
The typehead and popper.js dependencies are injected by the blacklight 7 asset generator.
=> Add javascript assets

app/controllers/statistics_controller.rb, app/views/shared/_statistics_navbar.html.erb, app/views/statistics/show.html.erb, config/initializers/spotlight_initializer.rb, config/locales/en.yml, config/routes.rb, db/seeds.rb, spec/features/statistics_spec.rb
=> Add a Statistics MainNavigation item and page for exhibits.

app/controllers/catalog_controller.rb
In English:
In Arabic:
(Note that the record only has Arabic values for some fields (e.g. title, rights), and only English/none (but effectively English) for other fields (e.g. language, type))
Display multilingual metadata using the rules from #589 (prefer the current language, fall back to any other values in a prescribed order) without adding duplicate index fields for each language. 
Fixes #589
=> Add support for multilingual index, show, and title fields 

app/controllers/catalog_controller.rb
These tools need to be explicitly added in Blacklight 7.
=> Add default results tools from blacklight

app/views/spotlight/shared/_curation_sidebar.html.erb
This enables access to the Curation > Translations menu. This is necessary for translating about pages, browse categories, and some navigation elements.
=> Add translations menu from upstream

config/environments/development.rb
To remove noise for troubleshooting RTL UI. @ggeisler, if this is useful for your local dev environment, please feel free to merge while we're away.
=> Enable i18n fallbacks in dev

app/assets/javascripts/application.js
This was how it was originally generated, and apparently worked fine at the time 🤷‍♂
=> Reorder the javascript to put popper above bootstrap

Gemfile, Gemfile.lock, app/assets/javascripts/blacklight_hierarchy.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/blacklight_hierarchy.scss, app/assets/stylesheets/facets.scss, app/assets/stylesheets/rtl.scss, app/controllers/catalog_controller.rb, app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
Closes #552 
To add support for a type/sub-type hierarchical facet.
n/a
=> Add a hierarchical facet (and show field) for the cho_type_facet field

app/controllers/catalog_controller.rb, app/controllers/statistics_controller.rb, app/models/statistics_dashboard.rb, app/views/statistics/_items.html.erb, app/views/statistics/show.html.erb, config/locales/en.yml, config/routes.rb, spec/features/statistics_spec.rb, spec/models/statistics_dashboard_spec.rb, spec/views/statistics/_items.html.erb_spec.rb
Part of #531 
To add item details to the statistics page.
=> Add the items section to the Statistics dashboard

app/assets/stylesheets/rtl.scss
=> Fix RTL styling for hierarchical facets

app/controllers/catalog_controller.rb, app/models/statistics_dashboard.rb, app/views/statistics/_contributors.html.erb, app/views/statistics/show.html.erb, config/locales/en.yml, spec/models/statistics_dashboard_spec.rb, spec/views/statistics/_contributors.html.erb_spec.rb, spec/views/statistics/_items.html.erb_spec.rb
Closes #688 
To add a contributors section to the dashboard.
=> Add a Contributors section to the Statistics Dashboard

app/assets/stylesheets/rtl.scss, app/processors/bidi_wrap.rb, config/initializers/blacklight.rb, spec/processors/autolink_spec.rb
This should stop it from being w…rongly influenc-ed/-ing by other content
=> Style metadata + facet values with bidi logic

.gitignore, Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb, app/resource_builders/dlme_json_resource_builder.rb, docker-compose.yml, spec/fixtures/json/iiif-single-image.json, spec/resource_builders/dlme_json_resource_builder_spec.rb
Solrize date ranges as integers. Fixes #697
Also:
* Use https URLs for GitHub-based repositories
* Update docker-compose configuration 
1. Remove explicit networks (this is not necessary); and
2. Use a mounted volume in the database container to store data
No
=> Solrize date ranges as integers

app/assets/stylesheets/application.scss, app/assets/stylesheets/bootstrap-overrides.scss
This change fixes #655 but in a way not originally specified.
Great so just load a specific font for a language selector, right this is easy?
https://www.w3.org/International/questions/qa-css-lang
Nope.. so that doesn't work because we need to be more specific. We aren't adding in `lang="ar"` wherever we display different language text.. but we could. But that might be hard.
Ok, so we can load fonts for different [unicode ranges](https://developer.mozilla.org/en-US/docs/Web/CSS/%40font-face/unicode-range). And this would be exactly what we want to enable a custom font for [Arabic unicode character ranges](https://en.wikipedia.org/wiki/Arabic_script_in_Unicode). Unfortunately it seems like browser implementation of how unicode range fallbacks work are different (as much as I can tell). …
=> Use Mada font (Latin and Arabic scripts) by default for DLME

app/models/statistics_dashboard.rb, app/views/statistics/show.html.erb, config/locales/en.yml, spec/features/statistics_spec.rb, spec/models/statistics_dashboard_spec.rb
In my environment I have the following transforms indexed:
- output-f9967242-f6c2-468e-bb6f-594caed0cf0f.ndjson (from dev)
- output-db22239a-81e4-4118-a667-26fb2b12f889.ndjson (from dev, partially indexed)
- output-12fa7465-adb2-4dc5-b9fd-c302986d45ec.ndjson (from dev, partially indexed)
As a follow on to #688, because, I....uh forgot this part.
=> Add the jumbotron section for contributors

app/controllers/catalog_controller.rb, app/processors/bidi_wrap.rb, spec/processors/bidi_wrap_spec.rb
=> Fixing the BIDI HTML wrapping

app/models/solr_document.rb, spec/models/solr_document_spec.rb
Non-transformed items (say, an uploaded item) don't have this field.
=> Guard against missing IR data

app/controllers/catalog_controller.rb
The masonry view we're getting from upstream is not RTL compatible. There may be some work we could do (#713) to make it work, but having this view is not a current requirement.
=> Disable the masonry view; part of #676

docker/Dockerfile
Adds imagemagick to Dockerfile.
Seems to work for me
Also aims to fix #723
=> Adds imagemagick to Docker fixes #722

app/assets/stylesheets/blacklight.scss
=> Set a max-width for document metadata

.circleci/config.yml
Follow-up to #730. This will hopefully keep our CircleCI builds humming along by caching JS dependencies installed by yarn. 
This change just follows CircleCI's Ruby language guide. 
https://circleci.com/docs/2.0/language-ruby/#config-walkthrough
Just the CircleCI config.
=> Store CircleCI yarn cache

app/views/catalog/_show_with_viewer.html.erb
This ensures the images don't overflow their column.
Before:
After:
=> Add the img-thumbnail class to show page images

app/assets/stylesheets/blacklight.scss
=> Use .metadata-value instead of the dd to avoid stomping on the bootstrap grid styles

app/controllers/s3_harvester_controller.rb
When an transform error is logged in `dlme-transform`, traject inserts a blank line, this strips those blank lines before comparing ids else a `non-unique ids` error is raised.
=> Do remove blank lines from json before checking ids

.codeclimate.yml, app/jobs/fetch_resources_job.rb
Do not try to index empty lines as they fail JSON validation.
=> Do not try to index empty lines in the json

app/assets/stylesheets/blacklight.scss
Closes #763
We _could_ push this upstream to Spotlight? 
N/A
=> Make sort per page buttons smaller

config/settings.yml
This adds incoming language codes from dlme-transform in order to keep DLME and DLME-Transform inline with each other for allowed languages.
=> Add new language codes

app/controllers/catalog_controller.rb
=> Guard against missing normalized date fields

app/assets/stylesheets/facets.scss, app/assets/stylesheets/rtl.scss
=> Remove the browser default padding for facet hierarchies

app/assets/stylesheets/rtl.scss
=> Display range limit as ltr when in rtl Arabic view fixes #777

app/assets/stylesheets/bootstrap-overrides.scss
There are places in the exhibit where certain elements are specified to be displayed in bold. Here's a couple of examples:
---
Current DLME doesn't show those as bold because the font stack doesn't include a heavier weight version of the Mada font, so we get this:
With this PR, DLME will look more like this:
N/A
=> Add 700 weight to font stack to get bold

Gemfile, Gemfile.lock
Fixes #809 by using the locale as part of the cache key
[cache_with_locale](https://github.com/igorkasyanchuk/cache_with_locale)
> Automatically adding current application locale (I18n.locale) as a part of caching key in Rails views.
=> Add cache_with_locale; fixes #809

config/initializers/spotlight_initializer.rb
Hopefully this will avoid the timeout issues we were seeing and let us get exhibit content out easily.
=> Disable exporting resources or solr documents as part of the export process

app/assets/stylesheets/rtl.scss
=> BIDI isolate the document counter so it isn't influenced by the directionality of the title

app/controllers/session_displays_controller.rb, app/helpers/application_helper.rb, app/helpers/blacklight_helper.rb, app/views/shared/_contextual_result_info.html.erb, config/locales/en.yml, config/routes.rb, config/settings.yml, spec/controllers/session_displays_controller_spec.rb, spec/features/contextual_message_spec.rb
To fix #805
I'm not sure how we are going to provide a link within this alert to a user created about page. Any thoughts?
=> Setup contextual alert dismissable for search results fixes #805

config/i18n-tasks.yml
So that when we report on/test our i18n health these admin-only facing keys are ignored.
=> Add admin facing DLME transform labels to the ignore_missing list.

app/assets/stylesheets/dlme.scss
The typography of the main menu nav items is currently not too great, with somewhat small text (for an important menu, anyway) and dim colors. This PR updates the typography to address those issues (though further improvements might be coming when I get to the final visual design of the site). It also lightens the text color of the menu items in the topbar.
=> Update typography of main menu

app/assets/stylesheets/dlme.scss, app/views/statistics/_contributors.html.erb, app/views/statistics/_items.html.erb, app/views/statistics/show.html.erb
Just some minor styling updates to reduce height of jumbotrons and reduce section heading sizes a bit.
=> Update stats page jumbotron and heading sizes

app/assets/stylesheets/dlme.scss
The analytics numbers should be more prominent, so they catch the curator's attention and are more readable at a glance.
=> Update styling of Analytics > User Activity table

app/controllers/catalog_controller.rb
Closes #843 (or at least is a temp. workaround)
We currently configure a different facet field for each locale a user might use (en, ar) and display that based on the current locale.  This is also extending to the admin page.  This means that currently re-ordering / enabling / disabling facets in the admin under the English locale does not affect the display of the Arabic facets in the Arabic display.  There also appears to be an issue w/ the Spotlight code that is dropping some attributes from the config when the form is saved **without** that field in the page/form (illustrated in the gif below).
This PR allows the fields for each locale to show up on the `Spotlight::SearchConfigurationsController` (which is where facets are configured) which gets us around the dropping of data and/or …
=> Display fields on the facet configuration page regardless of locale.

config/honeybadger.yml
Currently we're logging 404s to honeybadger, but these need not be logged.
no.
=> Don't send not-found errors to honeybadger

app/models/statistics_dashboard.rb, app/views/statistics/_contributors.html.erb, config/locales/en.yml, spec/models/statistics_dashboard_spec.rb, spec/views/statistics/_contributors.html.erb_spec.rb
Closes #883 
Institutions can exist in multiple countries so we need to display all of them in the dashboard (we were using just the first returned in the pivot facet response for display).
n/a
Using the AIMS transform from dev on 3/12/2020
=> Allow contributing institutions to exist in more than one country.

Gemfile.lock, app/assets/javascripts/range_limit_config.js
To wrap up work on #765, primarily configuring flot to no longer display the selection decorations/handles on the year histogram.
n/a
=> Update the range limit plugin and configure

app/views/statistics/_contributors.html.erb, app/views/statistics/_items.html.erb, app/views/statistics/show.html.erb, config/locales/en.yml, spec/features/statistics_spec.rb, spec/views/statistics/_contributors.html.erb_spec.rb
=> Use number_with_delimeter helper on statistics page to add commas

app/controllers/catalog_controller.rb
Assuming https://github.com/sul-dlss/dlme/blob/master/solr/config/solrconfig.xml#L92 matches what's in production, this configuration was wrong,
=> Use the right qf parameters for title searches

app/controllers/catalog_controller.rb
Local params were (effectively) disabled back in Solr 7.2 and there's no reason to use them here.
Probably fixes #914, unless there's yet more things wrong with the current configuration
=> Stop using local params for solr query parameters

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb
Fixes #922 by making the raw endpoint accessible with e.g. `?raw=true`.
=> Allow the raw doc to be accessed using a query parameter

app/controllers/statistics_controller.rb, app/models/statistics_dashboard.rb, spec/controllers/statistics_controller_spec.rb
=> Remove field-specific configuration from the statistics dashboard query

app/controllers/statistics_controller.rb, spec/features/statistics_spec.rb
=> Keep the CatalogController search fields; fixes #944

app/assets/stylesheets/dlme.scss, app/assets/stylesheets/variables.scss, app/views/shared/_header_navbar_masthead.html.erb
General styling updates to get the site looking a little better and coordinate with the recent masthead update. There will be more fine-tuning to do later, but I'd like to get the font updates done next and return to make any further styling updates after we're happy with font sizing, etc.
---
---
=> Update styling of masthead, footer, facets, etc.

app/assets/stylesheets/dlme.scss
Closes #880.
This is for the email announcements signup form that is hosted by CLIR that we display on an About page. @waynegraham made some styling updates to the form itself and this PR includes a couple more on the `<iframe>` element to remove the border and change the width from an explicit setting to `100%`. I think these changes make the embedded form work pretty well in the about page context, at any browser width.
Note that my SCSS selector here will match any iframe we add to a DLME about page. I don't think that's a problem since we probably don't want a border or explicit width on any other iframe we might add to an about page, but if we end up wanting to make this more targeted it should be easy to do by using an attribute selector that references the URL of the form we're …
=> Remove border and explicit width on About page iframe

app/assets/stylesheets/dlme.scss
Links in the sidebar (About pages, Admin dashboard pages) get both underline and a background color on hover. They only need one indicator that they are being hovered/focused, so I removed the background color.
I don't think this change affects links in other contexts, which don't seem to have the double indicator issue.
=> Adjust hover styling on sidebar links

app/javascript/packs/mirador.js
Closes #637.
This PR updates a couple of the Mirador theme colors:
- canvas background - to be a bit darker than the default, which blends into the site background a bit too much
- primary color -  to match the link color we're using generally on the site; shows up as the blue top border, selected icon color, and link color within the viewer
Everything else seems configured how we want it for DLME, unless I'm missing something.
One exception might be the Download & Share plugin. I assume it doesn't make sense to display that because of the way we're bringing in the IIIF items, but if whomever reviews this PR knows differently let me know.
=> Update theme colors for Mirador viewer

app/assets/stylesheets/rtl.scss
=> Don't do anything to the breadcrumb divider in RTL mode

app/assets/stylesheets/dlme.scss
The white background of the summary boxes felt a bit too stark to me. 
With this PR they now look like below, which still doesn't feel great but maybe a slight improvement until I think of something better...
=> Adjust background of stats summary boxes

app/assets/stylesheets/dlme.scss, app/assets/stylesheets/rtl.scss
Closes #966.
- Reduces indentation of second-level values
- Increases width values can take
Together these reduce the frequency of having Type facet values that wrap oddly.
These examples are the worst case (narrowest) viewport width:
---
=> Reduce indent of nested hierarchical facet values

app/assets/stylesheets/rtl.scss
There were some adjustments needed in RtL mode to get more desirable alignment of site logo and main menu elements.
=> Make some RtL adjustments to masthead elements

config/locales/ar.yml
Add a space after middot so it looks less like a period
n/a
=> Add space after middot in Arabic translation

app/assets/stylesheets/dlme.scss, app/assets/stylesheets/rtl.scss
Closes #987.
- Not enough vertical spacing in section heading when in Arabic
- Section items indented too far to the right
=> About page heading spacing

app/assets/stylesheets/rtl.scss
=> Add horizontal spacing to Edit button in RtL

app/assets/stylesheets/rtl.scss, app/views/statistics/_contributors.html.erb, app/views/statistics/_items.html.erb
This brings the statistics page inline with metadata display practices elsewhere in the app.
=> Add BIDI markup for statistics page data

app/models/statistics_dashboard.rb, spec/features/statistics_spec.rb
Fixes part of #1003 by using the agg_data_provider_country field for data providers
=> Use agg_data_provider_country for item provider stats

app/controllers/catalog_controller.rb, db/migrate/20210112001854_change_per_page.rb, db/schema.rb
Part of sul-dlss/exhibits#1942
Blank spaces at the end of gallery results are problematic, this makes sure that the number of results returned will always fill the page.
=> Update the per-page config to be divisible by 3

config/locales/en.yml
Closes #1083 
To fix the HTML so the anchor tag was properly closed.
=> Close the link in the contextual_result_info note.

.circleci/config.yml
Available versions here: https://circleci.com/docs/2.0/building-docker-images/#docker-version
This fixes a typo
=> A follow on to #1101 fixing the docker version

app/controllers/concerns/multilingual_locale_aware_field.rb, config/settings.yml, spec/controllers/concerns/multilingual_locale_aware_field_spec.rb
In order to update the order of multilingual metadata fields displayed around the application.
Closes #1052 
N/A
Below is a list of the before/after states of what language tagged fields we attempt to display when the application's UI  has been set to a particular language.
Default display
<pre>"ar-Arab"
"ar-Latn"</pre>
<details>
<summary>Fallback display</summary>
<pre> "en"
"none"
"ar-Arab"
"ar-Latn"
"fa-Arab"
"fa-Latn"
"fr"
"he"
"ms"
"tr-Arab"
"tr-Latn"
"ur-Arab"
"ur-Latn"</pre>
</details>
Default display
<pre>"en"</pre>
<details>
<summary>Fallback display</summary>
<pre> "ar-Arab"
"ar-Latn"
"none"
"en"
"fa-Arab"
"fa-Latn"
"fr"
"he"
"ms"
"tr-Arab"
"tr-Latn"
"ur-Arab"
"ur-Latn"</pre>
</details>
Default display
<pre>"ar-Arab"</pre>
<details>
<summary>Fallback display</summary>
<pre> …
=> Update multilingual metadata display

app/controllers/catalog_controller.rb, app/controllers/image_proxy_controller.rb, app/models/solr_document.rb, app/presenters/dlme_index_presenter.rb, app/presenters/dlme_show_presenter.rb, app/presenters/dlme_thumbnail_presenter.rb, config/routes.rb, config/settings.yml, spec/controllers/image_proxy_controller_spec.rb, spec/models/solr_document_spec.rb, spec/presenters/dlme_thumbnail_presenter_spec.rb, spec/views/catalog/_show_with_viewer.html.erb_spec.rb
Fixes #1074
This adds a protected proxy for http images and disables http iiif content which we cannot view.
An additional thing added was the `loading="lazy"` attribute for images so we don't try and proxy non-visible images.
=> Fixes #1074, by proxying http only images and disabling http iiif content

Gemfile, Gemfile.lock
This was causing an issue in production https://app.honeybadger.io/projects/53082/faults/73653608
Related to #1074
=> Explicitly add HTTP gem dependency (only in dev, test currently)

app/controllers/image_proxy_controller.rb, spec/controllers/image_proxy_controller_spec.rb
This fixes an issue where http:// thumb urls that actually redirect to https:// are not followed.
@jacobthill is updating some of the transforms (contentdm) ones that presented this problem, but this will follow redirects in the future so that users won't notice any problems.
=> Make sure that we follow redirects for the proxy thumbnails

.circleci/config.yml, app/controllers/catalog_controller.rb, app/resource_builders/dlme_json_resource_builder.rb, solr/config/schema.xml, solr/config/solrconfig.xml
This PR makes some generally best-practice improvements to our solr tuning, including adding phrase boosts to ensure that matching multiple near-adjacent terms increase the document relevancy score.
In addition:
Fixes #1103: adds fielded search for identifiers (and removed the unused subject search)  
Fixes #1106: increase the mm, not to 100%, but allows some leeway with longer query strings
Fixes #1105: adds additional fields containing textual data to the catch-all field so.. all means all.
Also, language-specific catch-all fields have been added for Arabic and English text to allow some fuzzy matching (with stemming, etc applied) across the catch-all data.
=> Tweak solr for improved relevancy and user experience

app/views/spotlight/shared/_report_a_problem.html.erb, config/locales/en.yml, config/settings/test.yml, spec/features/contact_form_override_spec.rb
=> Update exhibit feedback form

app/assets/stylesheets/dlme.scss, app/assets/stylesheets/rtl.scss, app/controllers/catalog_controller.rb, app/controllers/record_feedback_controller.rb, app/models/record_feedback_form.rb, app/views/catalog/_record_feedback.html.erb, app/views/record_feedback/new.html.erb, config/locales/ar.yml, config/locales/en.yml, config/routes.rb, spec/controllers/record_feedback_controller_spec.rb, spec/features/record_feedback_spec.rb, spec/models/record_feedback_form_spec.rb
Closes #146
https://user-images.githubusercontent.com/96776/105427725-9b4ae980-5c02-11eb-99d4-fe1169339064.mov
Resulting email:
```
To: test@example.com
Cc: test@example.com
Message-ID: <600a16a99bb2e_12b0122588933a1@li-dl-7475-708c.local.mail>
Subject: DLME item feedback
Mime-Version: 1.0
Content-Type: text/html;
charset=UTF-8
Content-Transfer-Encoding: 7bit
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style>
/* Email styles need to be inline */
</style>
</head>
<body>
<p></p>
<p>From: &quot;&quot; &lt;&gt;</p>
<p>This site is great, and this record in particular is REALLY good!</p>
----
<dl>
<dt>REMOTE_IP</dt><dd>::1</dd>
<dt>USER AGENT</dt><dd>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) …
```
=> Add a feedback button to records

app/assets/stylesheets/custom_blacklight_range_limit.scss
Fixes #1141.
This PR removes the left indent facet value labels get when they wrap to multiple lines.
The indent makes sense for most facet value labels because it helps distinguish values that wrap from the next value in the vertical list of values. But in the Date range facet there is only ever one facet value displayed, and removing the left indent gives the value a bit more horizontal space to use before wrapping. So this change only affects the facet value label in the Date range widget and leaves facet value labels in other facets alone.
@jacobthill I can't reproduce your screenshot in #1141, where the date value wraps several times. I tried the three main browsers with the same date values and all look like my Before screenshot above. 
In any case, this is a worthwhile thing to do …
=> Remove indent on Date Range facet value label

app/assets/stylesheets/dlme.scss
This is pretty subtle but the facet headers are using shades of gray that are close but _different_ than the background color/border colors of the gallery view thumbnail container. They either need to be noticeably different or the same, so this PR makes them use the same colors.
=> Adjust facet header background color to match gallery thumb background color

app/assets/stylesheets/blacklight_gallery.scss
A ramification of the recent change to hide the metadata field label in gallery view is that the metadata field values only have 9 cols in the metadata display area (because the field label gets 3 cols, which aren't displayed now). This leaves extra unused space (3 cols worth) in each line of metadata, which causes text wrapping sooner than it needs to:
The value indicated above wraps to 3 lines.
This PR overrides the column specification for the metadata field values in gallery view, giving them all 12 columns to work with. As a result, the value above now only requires 2 lines:
---
The effect is more dramatic in other records with longer metadata values (that I no longer have in my local index to use as examples).
The only drawback I see with this is if we ever change our mind and want …
=> Override column specification for gallery view metadata

config/initializers/riiif.rb
DEPRECATION WARNING: Riiif::Engine.config.cache_duration_in_days is deprecated; use #cache_duration instead and pass a fully-qualified date (e.g., `3.days`).
=> Use non-deprecated riiif cache config

app/assets/stylesheets/blacklight_gallery.scss
This is a first-pass at addressing @mwerla's [concern about the height of thumbnail images](https://github.com/sul-dlss/dlme/issues/1136#issuecomment-771598801) in gallery view. We can adjust the `max-height` value later after we assess the tradeoffs with the value set in this PR.
The issue addressed is that when there is a very vertically-oriented image in the gallery view results, it creates a very tall thumbnail area and forces the other items in its row to stretch to a unusually tall height. I went with limiting the height of thumbnail images to `200px` in this PR, which is a compromise between limiting the height of images while not reducing the width too much.
Indicated item creates very tall row with a lot of empty space in its neighbor items.
Indicated item's height is limited, …
=> Limit height of gallery view thumbnails

Gemfile, Gemfile.lock, app/assets/stylesheets/blacklight_gallery.scss, app/assets/stylesheets/dlme.scss, app/controllers/catalog_controller.rb, app/presenters/dlme_thumbnail_presenter.rb, spec/presenters/dlme_thumbnail_presenter_spec.rb
A follow on to upstream work in Spotlight and Blacklight-Gallery, this supports the upstream changes made there.
We should hold until Blacklight v7.15.0 is released with the thumbnail arity enhancement
Update: Now updated!
=> Update configuration to support blacklight-gallery 2.1.0 -> 3.0.1

app/models/dlme_json.rb, spec/models/dlme_json_spec.rb
To allow the Add Items via DLME JSON to work again.
This is in the documentation, just wasn't working any longer
=> Allow nil URLs for DLMEJson (since direct JSON uploads have no URL)

Gemfile.lock
=> Update spotlight again to get browse group translations

app/assets/stylesheets/blacklight_gallery.scss
Fixes #1202.
This PR ensures the thumbnail container in gallery view takes 100% of the available column width, so when an item's contents are relatively narrow, its thumbnail container will still be the maximum width. This ensures all containers on the page have the same width and things look nice and even.
=> Ensure gallery thumb background uses 100% width

config/i18n-tasks.yml, config/locales/ar.yml, config/locales/en.yml, spec/controllers/record_feedback_controller_spec.rb, spec/features/record_feedback_spec.rb
To achieve synergy between the contact us and record feedback form flash messages
Closes #1208 
N/A
After submitting record feedback:
=> Update Record Feedback flash message to match the Contact Us text

app/assets/stylesheets/blacklight_gallery.scss
Fixes #1206.
This fix will wrap long strings to prevent them from overflowing the thumbnail container. It applies to any metadata values in gallery view, but there's no real effect on normal values with words and spaces.
(In case it's relevant to anyone, the before issue isn't present in Firefox, it seems to handle the wrapping without the need for this fix. But Safari and Chrome do need it.)
=> Force long continuous strings to wrap in gallery view

config/environments/production.rb
Part of #1225 
I'm seeing a reduction in production `application.js` size of:
3937039 -> ﻿1699385
=> Minify our JavaScript in production

config/puma.rb
Enabling workers to test the impact of web concurrency on performance.
=> Enable web concurrency workers in puma config

app/jobs/fetch_resources_job.rb
Trying to get a better timing estimate of data loading jobs as well as show that they have started by indicating the file being loaded.
=> Add begin data load job logging

app/assets/javascripts/analytics.js, app/views/layouts/spotlight/base.html.erb, app/views/shared/_analytics.html.erb, app/views/shared/_footer.html.erb
=> Use Google Tag Manager to manage analytics

app/jobs/fetch_resources_job.rb, spec/jobs/fetch_resources_job_spec.rb
Touching the exhibit busts caches (among other things); instead, we should wait until the end of the batch.
=> Only touch the exhibit after the whole batch is complete to avoid unnecessary thrashing

.circleci/config.yml
Catching up on moving to `main` as the default branch.
=> Update master to main in circleci

config/puma.rb
This is apparently a thing people do when running puma in ECS 🤷‍♂️
=> Persistent timeout

README.md, docker-compose.yml
At some point in the recent past (https://github.com/localstack/localstack/issues/3080) the individual ports used by each localstack service is now gated through an edge service port.
This fixes docker-compose.yml and README instructions around that change.
BEFORE:
```
❯ AWS_ACCESS_KEY_ID=999999 AWS_SECRET_ACCESS_KEY=1231 aws sns \
--endpoint-url=http://localhost:4575 create-topic \
--region us-east-1 \
--name dlme-transform
Connection was closed before we received a valid response from endpoint URL: "http://localhost:4575/".
```
AFTER:
```
❯ AWS_ACCESS_KEY_ID=999999 AWS_SECRET_ACCESS_KEY=1231 aws sns \
--endpoint-url=http://localhost:4566 create-topic \
--region us-east-1 \
--name dlme-transform
{
"TopicArn": "arn:aws:sns:us-east-1:000000000000:dlme-transform"
}
```
=> Update localstack in docker-compose and README as ports changed

README.md
follow on to https://github.com/sul-dlss/dlme/pull/1304
i found that when i ran the local transform as it was, i got `upload failed: output/output-ae7331e3-ef91-43ff-826a-1dcbc1c2c60f.ndjson to s3://dlme-transform/output-ae7331e3-ef91-43ff-826a-1dcbc1c2c60f.ndjson Could not connect to the endpoint URL: "http://localhost:4572/dlme-transform/output-ae7331e3-ef91-43ff-826a-1dcbc1c2c60f.ndjson"`.  with this change, i got `upload: output/output-e2244b2e-88d2-41fd-b9bb-7e0deec2b2a1.ndjson to s3://dlme-transform/output-e2244b2e-88d2-41fd-b9bb-7e0deec2b2a1.ndjson` and no error messages.
yup
=> fix transform command in local dev instructions

spec/fixtures/json/iiif-single-image.json, spec/resource_builders/dlme_json_resource_builder_spec.rb
This removes the real princeton URL to a thumbnail from a iiif fixture. If the thumbnail is unreachable, the timeout breaks tests and builds.
```
2021-08-12 01:55:39 +0000 Rack app ("GET /image_proxyurl=http%3A%2F%2Flibimages.princeton.edu%2Floris2%2Fpudl0100%252Fposters%252Feg1_0095%252F00000001.jp2%2Ffull%2F200%2C%2F0%2Fdefault.jpg" - (127.0.0.1)): #<Rack::Timeout::RequestTimeoutError: Request ran for longer than 60000ms >
F2021-08-12 01:56:40 +0000 Rack app ("GET /image_proxyurl=http%3A%2F%2Flibimages.princeton.edu%2Floris2%2Fpudl0100%252Fposters%252Feg1_0095%252F00000001.jp2%2Ffull%2F200%2C%2F0%2Fdefault.jpg" - (127.0.0.1)): #<Rack::Timeout::RequestTimeoutError: Request ran for longer than 60000ms >
F.2021-08-12 01:57:43 +0000 Rack app ("GET …
```
=> Remove real URL from test so timeouts do not break build

config/environments/development.rb, docker-compose.yml
Adding the binding to the rails server command allows docker-compose to be used for local development.
Fixes #831  - and allows development with all components of the application stack
=> Set the host binding for local docker app

Gemfile, Gemfile.lock, Guardfile
This adds the guard-rspec gem to the development group so that we can run guard during development.
```
bundle exec guard
```
will follow changes during active development and run the associated tests in real time.
=> Add guard-rails to development to watch test results

app/controllers/transform_results_controller.rb, spec/requests/transform_result_spec.rb, spec/services/resource_remover_spec.rb
The excessively long list of transform results is unwieldy and not very useful to the data manager. As part of #1153 we will no longer be using uuids to create unique transformation files. Instead we will be using data_path based names and update the record here in order to maintain a cleaning and more useful user experience.
=> Update existing transform_result record instead of creating a new one each time

lib/tasks/transform.rake
This is a small rake task to clear out existing transform results. This will be run as a one off ECS task when needed so there is no need to expose this in the UI.
=> Add a simple rake task for purging transform results

.circleci/config.yml
I found an issue with the staging query for the cluster. The current case returns both `dlme` and `dlme-uat` which causes an error when trying to update the tasks for stage. This limits the cluster arn query to just `dlme`.
=> Fix the query for the dlme stage cluster arn

.circleci/config.yml, Gemfile.lock
Maintenance to update circleci images from `circleci` prefixes that were deprecated on 12/31.
=> Update to non legacy circlci images

app/models/statistics_dashboard.rb, app/views/statistics/_contributors.html.erb, spec/models/statistics_dashboard_spec.rb
The `agg_data_provider_*` and `agg_provider_*` fields do not follow the same pattern as other locale aware fields. This PR adds handling for these fields and fixes the click to search by institution feature on the statistics page.
=> Special handling for locale aware provider_facet_field. Fixes #1349

.circleci/config.yml
Apparently pip is no longer available after sudo'ing, but is also seemingly not a requirement.
=> Don't sudo to install the aws cli tools

.circleci/config.yml
Pushing the image tagged with the SHA1 seems to be conventional practice. If nothing else, this'll let us take a look at what's changed over time 🤷‍♂️
=> Tag and push new docker images with the sha1

app/controllers/catalog_controller.rb
=> Configure additional facet fields.

app/models/solr_document.rb, config/initializers/mime_types.rb
Fixes #1467.
This should allow us to slurp search results and single documents into a development environment without too much fuss by tacking on the format (e.g. https://dev.dlmenetwork.org/library/catalog.ndjson, or with any combination of search parameters).
=> Export documents as ndjson

app/assets/stylesheets/dlme.scss
Fixes #1497 
I removed this styling tweak from the upstream Spotlight PR and brought it down to DLME, because as @cbeer pointed out, it's very specific to DLME.
Before:
After:
=> Only display 1 line of title in breadcrumb

app/javascript/packs/mirador.js, package.json, spec/features/mirador_viewer_spec.rb
Fixes #1350 
- Adds plugin to package.json
- Enables plugin in config
- Checks for plugin existence in spec
=> Add Mirador Image Tools plugin

config/environments/production.rb
It removes too much information and makes the logs harder to investigate.
=> Disable lograge compact logging

solr/config/schema.xml
Reverting the change to add docValues to the Solr schema for now. It may still be worth doing, but there are some details to work out like the (suspected) slight increase in index size and a field size limit  encountered on dev for `__raw_resource_json_ss`
=> Revert docValues=true setting in solr schema

docker/invoke_fetch_s3.sh
This was useful to debug triggering indexing from airflow but is not necessary and may overly fill the logs...
=> Undo rake debugging trace that is no longer needed

Gemfile, Gemfile.lock
i18n-js was added in:
https://github.com/sul-dlss/dlme/pull/902/files
to support changing the date picker translations. 
I18n-js v4 was a ground-up rewrite, and will take some work to (re)install. Notably, the asset pipeline "magic" has been replaced by an explicit "export" step + CLI tool. We'll have to figure out how to add that step for dev + production builds. This seems like an excessive amount of work to export 4 keys 😬 .
=> Pin i18n-js

app/views/spotlight/shared/_curation_sidebar.html.erb
This restores the bulk update link to the exhibit sidebar that is clobbered from the upstream spotlight code (https://github.com/projectblacklight/spotlight/blob/main/app/views/spotlight/shared/_curation_sidebar.html.erb)
=> Restore clobbered link to bulk updates on exhibit dashboard

config/database.yml
We don't need the production environment as that is provided by puppet (`capistrano_db_yaml: true`)
=> Update database config for on-prem usage

config/initializers/carrierwave.rb, config/initializers/riiif.rb, config/settings.yml
What this pull request does (#1659 ):
- With image storage being moved off S3 to on premise, we no longer need S3 handling for images.  
- Settings.yml no longer requires an S3 bucket key
- The file "carrierwave.rb" can be removed, since the entirety of that code handles the condition for the S3 bucket.
- When the S3 handling is removed from riiif.rb, the file matches the original Spotlight file https://github.com/projectblacklight/spotlight/blob/main/lib/generators/spotlight/templates/config/initializers/riiif.rb .  Removing the file results in an error (on my local machine) so the file remains although, after the removal of S3 specific handling, the code is identical to the one in Spotlight. (Please feel free to let me know if, instead, the code should work without the riiif file …
=> Removing S3 handling

config/environments/production.rb
This restores the Rails defaults: https://github.com/rails/rails/blob/fad9050d80cb4d2d7c482311832724558bbfbbc2/railties/lib/rails/generators/rails/app/templates/config/environments/production.rb.tt#L81
=> Disable the queue name prefix

config/environments/production.rb
The rails default for reconnect-attempts is 0.
However on the main branch, they remove the default and it falls back to the Redis default (which is 2) https://github.com/rails/rails/commit/c8d8f09f56ffde6ecbb498cec8206fa5c72b8f49
=> Configure redis cache to reconnect

app/views/statistics/_items.html.erb
This is preventing upgrades to Blacklight 8, where the method has been removed
=> Stop using deprecated method facet_display_value

app/views/layouts/spotlight/base.html.erb, app/views/shared/_i18n_js.html.erb
This avoids a "Uncaught ReferenceError: Spotlight is not defined"
=> Defer config until script has loaded

Gemfile, Gemfile.lock
This should fix the bug where spotlight was not compatible with turbo which made it impossible to create a new browse group.
=> Update to spotlight 3.6.0.beta4

app/assets/stylesheets/dlme.scss
Before (masthead image doesn't go under header; menu is too long):
After:
=> Adjust positioning of header menu on mobile

app/components/multilingual_date_range_component.rb
Closes #1702 
The other option key/values passed to range_limit_panel_url weren't being used so I've dropped them, see: https://github.com/projectblacklight/blacklight_range_limit/commit/32d073f9a8d8427b047f8bcad2cab76e25ad1636#diff-e1b174fbb4b0c2595fdb35078674ca8d1796dca15eef88ec137981003d315d0fR10
=> Use search_facet_path directly instead of deprecated method

app/assets/javascripts/analytics.js, app/views/shared/_analytics.html.erb, app/views/shared/_body_preamble.html.erb, config/initializers/spotlight_initializer.rb
- Configure analytics with GA4
- Use GA4-compatible pageview tracking with turbo
See related PR https://github.com/sul-dlss/puppet/pull/9225 to turn off debug mode in prod. You can view events live in staging or local dev using [DebugView](https://support.google.com/analytics/answer/7201382?hl=en); they don't persist or show up in data otherwise.
=> Use Google Analytics v4

config/initializers/config.rb, config/initializers/rack-attack.rb, config/settings.yml
Ref #1572
Since this sets the default to disabling search throttling, we can test that it's working correctly and then file a PR in puppet to set `THROTTLE_SEARCHES` to true for prod only to re-enable it in that environment. After that I think the issue can be closed.
=> Allow disabling search throttling via config or envvar

app/controllers/catalog_controller.rb
This fixes an issue where browse categories appeared to display
all items instead of filtering to the category, because we were
not sending the browse category ID to solr. Blacklight 8 strips
out unknown params from the search unless they are specified
in config.search_state_fields.
See related https://github.com/projectblacklight/spotlight/issues/2966
=> Explicitly allow browse category ID in search state

app/processors/join.rb, spec/processors/join_spec.rb
This code handles the error described in https://github.com/orgs/sul-dlss/projects/53?pane=issue&itemId=21913854 .  By distinguishing between an autocomplete request, where we do want strings returned instead of arrays, and other JSON API requests related to the catalog controller where we want arrays returned, we should be able to handle the to_str error which occurs because the autocomplete code in Spotlight was receiving an array instead of the expected string.  Rspec tests have been updated to reflect this difference between a regular JSON API catalog controller request and an autocomplete request.  Added the action name "index" for the regular JSON API catalog controller, since that is one situation (when using the "/raw" option at the end of a catalog page) where the Join render is …
=> Handle to str error

Gemfile, Gemfile.lock
Because we're not using S3 anymore
=> Remove carrierwave-aws gem

app/assets/stylesheets/footer.scss, app/assets/stylesheets/rtl.scss, app/assets/stylesheets/variables.scss, app/views/shared/_footer.html.erb, config/locales/ar.yml, config/locales/en.yml, config/settings.yml
Closes #1819 
@astridu this implementation differs slightly from what's specified in #1819. I opted to align the accessibility statement with the text in the main body of the page to reduce awkward breaks in the text at different screen sizes.
=> Add accessibility contact information to footer

Gemfile, Gemfile.lock, package.json, yarn.lock
JS imports are broken in Blacklight 8.2
Commit that broke it: https://github.com/projectblacklight/blacklight/commit/d8c0ec4435db34b85f83a2e4799bc15b0469ef27
Proposing a revert: https://github.com/projectblacklight/blacklight/pull/3164
=> Pin blacklight to 8.1.0 until JS in 8.2 is fixed

config/initializers/rack-attack.rb
May address #1572. Jacob estimates that the people doing the collection work will make about 20 search requests over the course of 5 minutes. This adjust throttling so they are less likely to be blocked as they're working.
=> Adjust rack attack throttling

Gemfile, Gemfile.lock, bin/rails, bin/setup, config/application.rb, config/boot.rb, config/environment.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/content_security_policy.rb, config/initializers/filter_parameter_logging.rb, config/initializers/permissions_policy.rb
This needs to run `bin/rails active_storage:update` before being complete, but it's running into trouble:
```
bin/rails active_storage:update
DEPRECATION WARNING: DeprecatedConstantProxy without a deprecator is deprecated (called from <main> at /Users/jcoyne85/workspace/sul-dlss/dlme/config/application.rb:7)
DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.
Check the Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
for more information on how to upgrade.
(called from <main> at /Users/jcoyne85/workspace/sul-dlss/dlme/config/environment.rb:5)
PaperTrail 12.3.0 is not compatible with ActiveRecord 7.1.2. We allow PT
contributors …
```
=> Upgrade to rails 7.1

app/models/search_builder.rb, spec/models/search_builder_spec.rb
Fixes:
```
ActionView::Template::Error (undefined method `match?' for {"id"=>["p15795coll32:68160"]}:ActiveSupport::HashWithIndifferentAccess)
```
which occurs when an item is embedded in a search context, like the exhibit home page.
=> Check that search_state.query_param responds to match?

app/assets/stylesheets/rtl.scss, app/views/layouts/spotlight/base.html.erb
Fixes skiplink display issue in DLME.
Current prod:
With this PR:
=> Update skiplink classes for Blacklight 8

app/components/header_component.html.erb, app/components/header_component.rb, app/controllers/catalog_controller.rb
This avoids a deprecation warning from Spotlight
=> Extract a header component

app/assets/javascripts/blacklight_gallery.js, app/assets/javascripts/spotlight.js, app/javascript/entry.js, app/views/layouts/spotlight/base.html.erb, vendor/javascript/blacklight-hierarchy.js
Closes #1947
I missed that https://github.com/sul-dlss/dlme/pull/1934 deleted the Spotlight javascript.
Spotlight v4 depends on the Bootstrap jQuery integration, so the global jQuery *must* be the same jQuery that bootstrap 4 imports via the importmap. This requires rolling back part of my change from #1941.
blacklight-hierarchy needs jQuery, but I think we're fine to cheese that here in the vendor file. Blacklight-hierarchy doesn't get updated, and we need to replace the use of it anyway.
blacklight-gallery wants global jQuery. We can't provide that within the context of entry.js, we'd have to add rollup or change blacklight-gallery? For now, I've switched back to including via sprockets to see if it gets the site running again.
=> Restore Spotlight javascript

Gemfile.lock, app/views/layouts/spotlight/base.html.erb, spec/features/spotlight_frontend_spec.rb, yarn.lock
Spotlight 4.7.0 allows us to fix the Sir Trevor icon loading issue.
Added tests to check if the block editor & the icons render. I think this is a decent indicator if the spotlight-frontend JavaScript is actually running.
=> Update to Spotlight 4.7.0
